"""Initial frozen organization/geography/nutrition schema."""

from alembic import op
import sqlalchemy as sa

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "master_imports",
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_date", sa.String(length=10), nullable=False),
        sa.Column("version", sa.String(length=60), nullable=False),
        sa.Column("imported_by", sa.String(length=120), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "programmes",
        sa.Column("code", sa.String(length=60), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "regions",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("region_code", sa.String(length=40), nullable=False),
        sa.Column("capital", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("region_code"),
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "districts",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("assembly_type", sa.String(length=20), nullable=False),
        sa.Column("administrative_code", sa.String(length=40), nullable=True),
        sa.Column("capital", sa.String(length=120), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("effective_from", sa.String(length=10), nullable=True),
        sa.Column("effective_to", sa.String(length=10), nullable=True),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("version", sa.String(length=40), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("region_id", "name"),
    )
    op.create_index(op.f("ix_districts_region_id"), "districts", ["region_id"], unique=False)
    op.create_table(
        "password_resets",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token_hash"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("organization_type", sa.String(length=80), nullable=False),
        sa.Column("region_id", sa.String(length=36), nullable=False),
        sa.Column("district_id", sa.String(length=36), nullable=False),
        sa.Column("configuration", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["district_id"],
            ["districts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["regions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("organization_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_organization_id"), "audit_logs", ["organization_id"], unique=False
    )
    op.create_table(
        "indicators",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("programme", sa.String(length=60), nullable=False),
        sa.Column("definition", sa.Text(), nullable=False),
        sa.Column("numerator_definition", sa.Text(), nullable=False),
        sa.Column("denominator_definition", sa.Text(), nullable=False),
        sa.Column("target", sa.Float(), nullable=False),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("approval_reference", sa.String(length=250), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_indicators_organization_id"), "indicators", ["organization_id"], unique=False
    )
    op.create_table(
        "subdistricts",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("responsible_officer", sa.String(length=120), nullable=True),
        sa.Column("contact", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(
        op.f("ix_subdistricts_organization_id"), "subdistricts", ["organization_id"], unique=False
    )
    op.create_table(
        "facilities",
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("code", sa.String(length=50), nullable=True),
        sa.Column("facility_type", sa.String(length=60), nullable=False),
        sa.Column("subdistrict_id", sa.String(length=36), nullable=False),
        sa.Column("community", sa.String(length=120), nullable=True),
        sa.Column("ownership", sa.String(length=60), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("programmes", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["subdistrict_id"],
            ["subdistricts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "name"),
    )
    op.create_index(
        op.f("ix_facilities_organization_id"), "facilities", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_facilities_subdistrict_id"), "facilities", ["subdistrict_id"], unique=False
    )
    op.create_table(
        "communities",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("chps_zone", sa.String(length=100), nullable=True),
        sa.Column("facility_id", sa.String(length=36), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_communities_facility_id"), "communities", ["facility_id"], unique=False
    )
    op.create_index(
        op.f("ix_communities_organization_id"), "communities", ["organization_id"], unique=False
    )
    op.create_table(
        "operational_records",
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("facility_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("entered_by", sa.String(length=36), nullable=False),
        sa.Column("modified_by", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("import_batch", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_operational_records_facility_id"),
        "operational_records",
        ["facility_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_operational_records_kind"), "operational_records", ["kind"], unique=False
    )
    op.create_index(
        op.f("ix_operational_records_organization_id"),
        "operational_records",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "reports",
        sa.Column("facility_id", sa.String(length=36), nullable=False),
        sa.Column("period", sa.String(length=7), nullable=False),
        sa.Column("state", sa.String(length=30), nullable=False),
        sa.Column("values", sa.JSON(), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("amendment_reason", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("entered_by", sa.String(length=36), nullable=False),
        sa.Column("modified_by", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("import_batch", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("organization_id", "facility_id", "period"),
    )
    op.create_index(op.f("ix_reports_facility_id"), "reports", ["facility_id"], unique=False)
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_table(
        "clients",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("reference", sa.String(length=80), nullable=False),
        sa.Column("date_of_birth", sa.String(length=10), nullable=False),
        sa.Column("sex", sa.String(length=20), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("facility_id", sa.String(length=36), nullable=False),
        sa.Column("community_id", sa.String(length=36), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("entered_by", sa.String(length=36), nullable=False),
        sa.Column("modified_by", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("import_batch", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_clients_facility_id"), "clients", ["facility_id"], unique=False)
    op.create_index(
        op.f("ix_clients_organization_id"), "clients", ["organization_id"], unique=False
    )
    op.create_table(
        "memberships",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("facility_id", sa.String(length=36), nullable=True),
        sa.Column("community_id", sa.String(length=36), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["community_id"],
            ["communities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "organization_id"),
    )
    op.create_index(
        op.f("ix_memberships_organization_id"), "memberships", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_memberships_user_id"), "memberships", ["user_id"], unique=False)
    op.create_table(
        "actions",
        sa.Column("title", sa.String(length=180), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("facility_id", sa.String(length=36), nullable=True),
        sa.Column("client_id", sa.String(length=36), nullable=True),
        sa.Column("indicator_id", sa.String(length=36), nullable=True),
        sa.Column("assigned_to", sa.String(length=36), nullable=True),
        sa.Column("due_date", sa.String(length=10), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("entered_by", sa.String(length=36), nullable=False),
        sa.Column("modified_by", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("import_batch", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_to"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["indicator_id"],
            ["indicators.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_actions_facility_id"), "actions", ["facility_id"], unique=False)
    op.create_index(
        op.f("ix_actions_organization_id"), "actions", ["organization_id"], unique=False
    )
    op.create_table(
        "encounters",
        sa.Column("client_id", sa.String(length=36), nullable=False),
        sa.Column("facility_id", sa.String(length=36), nullable=False),
        sa.Column("programme", sa.String(length=60), nullable=False),
        sa.Column("visit_date", sa.String(length=10), nullable=False),
        sa.Column("measurements", sa.JSON(), nullable=False),
        sa.Column("assessment", sa.Text(), nullable=False),
        sa.Column("followup_date", sa.String(length=10), nullable=True),
        sa.Column("outcome", sa.Text(), nullable=True),
        sa.Column("risk", sa.String(length=30), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("organization_id", sa.String(length=36), nullable=False),
        sa.Column("entered_by", sa.String(length=36), nullable=False),
        sa.Column("modified_by", sa.String(length=36), nullable=True),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=True),
        sa.Column("import_batch", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["entered_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["facility_id"],
            ["facilities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["modified_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_encounters_client_id"), "encounters", ["client_id"], unique=False)
    op.create_index(op.f("ix_encounters_facility_id"), "encounters", ["facility_id"], unique=False)
    op.create_index(
        op.f("ix_encounters_organization_id"), "encounters", ["organization_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_encounters_organization_id"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_facility_id"), table_name="encounters")
    op.drop_index(op.f("ix_encounters_client_id"), table_name="encounters")
    op.drop_table("encounters")
    op.drop_index(op.f("ix_actions_organization_id"), table_name="actions")
    op.drop_index(op.f("ix_actions_facility_id"), table_name="actions")
    op.drop_table("actions")
    op.drop_index(op.f("ix_memberships_user_id"), table_name="memberships")
    op.drop_index(op.f("ix_memberships_organization_id"), table_name="memberships")
    op.drop_table("memberships")
    op.drop_index(op.f("ix_clients_organization_id"), table_name="clients")
    op.drop_index(op.f("ix_clients_facility_id"), table_name="clients")
    op.drop_table("clients")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_facility_id"), table_name="reports")
    op.drop_table("reports")
    op.drop_index(op.f("ix_operational_records_organization_id"), table_name="operational_records")
    op.drop_index(op.f("ix_operational_records_kind"), table_name="operational_records")
    op.drop_index(op.f("ix_operational_records_facility_id"), table_name="operational_records")
    op.drop_table("operational_records")
    op.drop_index(op.f("ix_communities_organization_id"), table_name="communities")
    op.drop_index(op.f("ix_communities_facility_id"), table_name="communities")
    op.drop_table("communities")
    op.drop_index(op.f("ix_facilities_subdistrict_id"), table_name="facilities")
    op.drop_index(op.f("ix_facilities_organization_id"), table_name="facilities")
    op.drop_table("facilities")
    op.drop_index(op.f("ix_subdistricts_organization_id"), table_name="subdistricts")
    op.drop_table("subdistricts")
    op.drop_index(op.f("ix_indicators_organization_id"), table_name="indicators")
    op.drop_table("indicators")
    op.drop_index(op.f("ix_audit_logs_organization_id"), table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("organizations")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("password_resets")
    op.drop_index(op.f("ix_districts_region_id"), table_name="districts")
    op.drop_table("districts")
    op.drop_table("users")
    op.drop_table("regions")
    op.drop_table("programmes")
    op.drop_table("master_imports")
    # ### end Alembic commands ###
